python TrainModle/train_cls_model.py \
    --model "model/llm/chinese-roberta-wwm-ext" \
    --train_path "data/classical_cls/cls_data_train.txt" \
    --dev_path "data/classical_cls/cls_data_test.txt" \
    --save_dir "checkpoints/wyw_classify" \
    --img_log_dir "logs/wyw_classify" \
    --img_log_name "RoBERTa" \
    --num_labels 2 \
    --batch_size 64 \
    --max_seq_len 128 \
    --valid_steps 5000 \
    --logging_steps 100 \
    --num_train_epochs 3 \
    --device "cuda:0"